language: c

sudo: false

env:
  - PHPENV_NATIVE_EXT=
  - PHPENV_NATIVE_EXT=1

install: git clone --depth 1 https://github.com/sstephenson/bats.git

script: PATH="./bats/bin:$PATH" test/run

notifications:
  email:
    on_success: never
