#!/usr/bin/env bash
set -e

find_version_file() {
  local root="$(pwd)"
  while [ -n "$root" ]; do
    if [ -e "${root}/.phpenv-version" ]; then
      echo "${root}/.phpenv-version"
      return 0
    fi
    root="${root%/*}"
  done
  return 1
}

DEFAULT_PATH="${HOME}/.phpenv/default"

find_default_version_file() {
  if [ -e "$DEFAULT_PATH" ]; then
    echo "$DEFAULT_PATH"
    return 0
  fi
  return 1
}

if [ -z "$PHPENV_VERSION" ]; then
  find_version_file || find_default_version_file || true
else
  echo "PHPENV_VERSION environment variable"
fi
