#!/usr/bin/env bash
set -e

# Read the first non-whitespace word from the specified file.
read_version_file() {
  local words version
  while read -a words; do
    version="${words[0]}"
    if [ -n "$version" ]; then
      echo "$version"
      break
    fi
  done < "$1"
}

DEFAULT_PATH="${HOME}/.phpenv/default"

if [ -z "$PHPENV_VERSION" ]; then
  PHPENV_VERSION_FILE="$(phpenv-version-origin)"

  if [ -n "$PHPENV_VERSION_FILE" ]; then
    PHPENV_VERSION="$(read_version_file "$PHPENV_VERSION_FILE")"
  else
    echo system > "$DEFAULT_PATH"
    PHPENV_VERSION=system
  fi
fi

if [ "$PHPENV_VERSION" = "system" ]; then
  echo "$PHPENV_VERSION"
  exit
fi

PHPENV_VERSION_PATH="${HOME}/.phpenv/versions/${PHPENV_VERSION}"

if [ -d "$PHPENV_VERSION_PATH" ]; then
  echo "$PHPENV_VERSION"
else
  echo "phpenv: version \`$PHPENV_VERSION' is not installed" >&2
  exit 1
fi
