#!/usr/bin/env bash -e

create_prototype_shim() {
  cat > .phpenv-shim <<SH
#!/usr/bin/env bash -e
exec phpenv exec "\${0##*/}" "\$@"
SH
  chmod +x .phpenv-shim
}

make_shims() {
  local glob="$@"

  for file in $glob; do
    local shim="${file##*/}"
    [ -e "$shim" ] || ln -f .phpenv-shim "$shim"
  done
}

mkdir -p "${HOME}/.phpenv/shims"
cd "${HOME}/.phpenv/shims"
rm -f *

create_prototype_shim
make_shims ../versions/*/bin/*

shopt -s nullglob
PHPENV_REHASH_PLUGINS=(/etc/phpenv.d/rehash/*.bash ${HOME}/.phpenv/phpenv.d/rehash/*.bash)
shopt -u nullglob

for script in ${PHPENV_REHASH_PLUGINS[@]}; do
  source $script
done

rm -f .phpenv-shim
