#!/usr/bin/env bash
set -e

PHPENV_VERSION="$1"
if [ -z "$PHPENV_VERSION" ]; then
  echo "usage: phpenv set-local VERSION" >&2
  exit 1
fi

# Make sure the specified version is installed
phpenv-prefix "$PHPENV_VERSION" >/dev/null

echo "$PHPENV_VERSION" > .phpenv-version
