#!/usr/bin/env bash -e

PHPENV_COMMAND="$1"
if [ -z "$PHPENV_COMMAND" ]; then
  echo "usage: phpenv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

PHPENV_COMMAND_PATH="$(phpenv-which "$PHPENV_COMMAND")"
PHPENV_BIN_PATH="${PHPENV_COMMAND_PATH%/*}"

shopt -s nullglob
PHPENV_EXEC_PLUGINS=(/etc/phpenv.d/exec/*.bash ${HOME}/.phpenv/phpenv.d/exec/*.bash)
shopt -u nullglob

for script in ${PHPENV_EXEC_PLUGINS[@]}; do
  source $script
done

shift 1
export PATH="${PHPENV_BIN_PATH}:${PATH}"
exec -a "$PHPENV_COMMAND" "$PHPENV_COMMAND_PATH" "$@"
