#!/usr/bin/env bash
set -e

if [ -n "$1" ]; then
  PHPENV_VERSION="$1"
elif [ -z "$PHPENV_VERSION" ]; then
  PHPENV_VERSION="$(phpenv-version-name)"
fi

if [ "$PHPENV_VERSION" = "system" ]; then
  PHP_PATH="$(phpenv-which php)"
  echo "${PHP_PATH%/*}"
  exit
fi

PHPENV_PREFIX_PATH="${HOME}/.phpenv/versions/${PHPENV_VERSION}"
if [ ! -d "$PHPENV_PREFIX_PATH" ]; then
  echo "phpenv: version \`${PHPENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$PHPENV_PREFIX_PATH"
