#!/usr/bin/env bash -e

expand_path() {
  local cwd="$(pwd)"
  cd "$1"
  pwd
  cd "$cwd"
}

remove_from_path() {
  local path_to_remove="$(expand_path "$1")"
  local result=""

  for path in ${PATH//:/$'\n'}; do
    path="$(expand_path "$path" || true)"
    if [ "$path" != "$path_to_remove" ]; then
      result="${result}${path}:"
    fi
  done

  echo "${result%:}"
}

PHPENV_VERSION="$(phpenv-version-name)"
PHPENV_COMMAND="$1"

if [ "$PHPENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${HOME}/.phpenv/shims")"
  PHPENV_COMMAND_PATH="$(command -v "$PHPENV_COMMAND")"
else
  PHPENV_COMMAND_PATH="${HOME}/.phpenv/versions/${PHPENV_VERSION}/bin/${PHPENV_COMMAND}"
fi

shopt -s nullglob
PHPENV_WHICH_PLUGINS=(/etc/phpenv.d/which/*.bash ${HOME}/.phpenv/phpenv.d/which/*.bash)
shopt -u nullglob

for script in ${PHPENV_WHICH_PLUGINS[@]}; do
  source $script
done

if [ -x "$PHPENV_COMMAND_PATH" ]; then
  echo "$PHPENV_COMMAND_PATH"
else
  echo "phpenv: $PHPENV_COMMAND: command not found" >&2

  versions="$(phpenv-whence "$PHPENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these PHP versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
