#!/usr/bin/env bash
set -e

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(readlink "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export PATH="${libexec_path}:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "phpenv 0.1.1\n$(phpenv-help)" >&2
  ;;
* )
  command_path="$(command -v "phpenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "phpenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
